environment:
  name: DEV
server:
  port: 8080
log4j:
  appender:
    stdout: org.apache.log4j.ConsoleAppender
    stdout.Target: System.out
    stdout.layout: org.apache.log4j.PatternLayout
    stdout.layout.ConversionPattern: '%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n'
  logger:
    org:
      hibernate: trace
  rootLogger: DEBUG, stdout
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      springframework: error
spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/demoprojectdb
    username: postgres
  jpa:
    properties:
      hibernate:
        SQL: debug
        format_sql: true
        generate_statistics: false
        show_sql: true
        type:
          descriptor:
            sql: trace
    show-sql: true
keycloak:
  credentials.secret: 6a06b69f-8108-4d40-af64-ed1325385c5d
  auth-server-url: http://localhost:8100/auth
  realm: DemoProjectRealm
  resource: DemoProjectRestApiClient
  cors: true
